### ISSUE TITLE
Command to add fonts

### ISSUE THREAD

**Issue by acauamontiel** [raphaklaus/fontwr#5]
Sometimes you need to add custom or paid fonts in your project.

Would be nice if there was a command like `fontwr add {{fontname}}`, where `{{fontname}}` is the path to the font folder.

Obviously the added fonts should be placed into the system's font directory.

**Comment by raphaklaus** [comment]
Thanks for the suggestion, I've added this case into #6!

Digging in, `{{fontname}}` could be a directory or a single file.

If `{{filename}}` is a directory, then: fetch all .ttf files, place them inside tmp/ and pipe them into CLI conversion method so user can choose what format and in the end generate font-face.

if `{{filename}}` is a single file, then: fetch it, place inside tmp/ and pipe it into CLI conversion method so user can choose what format and in the end generate font-face.

However, the added fonts only should be placed into system's font directory if **-g** option is present.

Any PR is welcome, but I recommend try after [1.0.0-beta.2](https://github.com/raphaklaus/fontwr/milestones/1.0.0-beta.2)
